# output dir will be created by hydra
data_dir: /cms/ldap_home/haeyun/CPVtop/nu2flows/v2flow_sample/ 
output_dir: /cms/ldap_home/haeyun/CPVtop/nu2flows/Saved_Networks/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
